---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-eks-nodegroup-ks
  namespace: flux-system
spec:
  timeout: 2m
  path: ./_artifacts/20-tf-eks-nodegroup
  interval: 5m
  prune: true
  force: false
  sourceRef:
    name: flux-system
    kind: GitRepository
  dependsOn:
  - name: tf-controller
