---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    cluster: c00-tf-cluster
resources:
- ../../_features/00-tf-controller/tf-controller-ks.yaml
- ../../_features/10-infra/infra-ks.yaml
