---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: s3-bucket
  namespace: flux-system
spec:
  interval: 5m
  path: ./_artifacts/40-zz-terraform
  approvePlan: "auto"
  backendConfig:
    disable: true    
  cliConfigSecretRef:
    name: tfc-cli-config
    namespace: flux-system    
  varsFrom:
  - kind: Secret
    name: aws-vars
  - kind: Secret
    name: tfc-helloworld-output
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
