---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  timeout: 2m
  path: ./_artifacts/00-tf-controller
  interval: 5m
  prune: true
  force: false
  sourceRef:
    name: flux-system
    kind: GitRepository
